AddCSLuaFile("cl_init.lua")
-- AddCSLuaFile("shared.lua")
AddCSLuaFile("cl_intro_logo.lua")
AddCSLuaFile("cl_credits.lua")
AddCSLuaFile("cl_youhaveperished.lua")
-- include("shared.lua")
include("sv_intro_logo.lua")
include("sv_credits.lua")
include("sv_youhaveperished.lua")
